woowa-techcamp-2021/cashbook-10

client/.babelrc
client/.prettierrc
client/package-lock.json
client/package.json
client/src/assets.d.ts
client/src/index.html
client/src/index.ts
client/src/styles/index.scss
client/src/styles/reset.scss
client/tsconfig.json
client/webpack.config.js

웹팩 설정 했습니다 :)
- 파비콘은 아직 못 넣었어요 ㅠ_ㅠ

FE 셋업 (웹팩, 바벨, 등)

---

client/src/index.html
client/src/index.ts
client/src/lib/woowact/app/App.ts
client/src/lib/woowact/core/Component.ts
client/src/lib/woowact/core/Diff.ts
client/src/lib/woowact/core/myJSX.ts
client/src/lib/woowact/index.ts
client/src/pages/ExamplePage.ts
client/src/pages/index.ts
client/src/utils/parser.ts
client/src/utils/selector.ts

프론트엔드 컴포넌트 구조 구축 및 가상돔 기본 구성 적용
https://user-images.githubusercontent.com/35447853/127207378-b8220265-c7cb-4ed5-bfee-bab95fe25f06.mov
- 아직 가상돔을 제대로 적용하지 않았습니다..!
- 내일 Diff 알고리즘 잘 짜서 적용해볼게요~!
- 라우터도 필요하면 써봅시다..!
- myJSX 파서 저번주에 만든거 그대로 사용해도 될 것 같아서 가져왔습니다 :)

[FE] 프론트엔드 컴포넌트 구조 구축 및 가상돔 기본 구성 적용

---

server/package.json
server/src/index.ts
server/src/routers/apis/authRouter.ts
server/src/routers/apis/categoryRouter.ts
server/src/routers/apis/historyRouter.ts
server/src/routers/apis/paymentRouter.ts
server/src/routers/apis/userRouter.ts
server/src/routers/index.ts

API 구현을 위해 기본적인 라우터 환경을 구축했습니다!

[BE, 페어 프로그래밍] API 기본 환경 구축 (라우터)

---

server/src/controllers/category.controller.ts
server/src/controllers/index.ts
server/src/routers/apis/categoryRouter.ts
server/src/services/category.service.ts

resolve #16
카테고리 API 구현 및 응답에서 공통적으로 처리할 기능을 구현하였습니다.  
- 컨트롤러의 index.ts는 공통 사용 기능이므로 불편하거나 궁금한 부분이 있다면 코드 리뷰에 질문 남겨주시기 바랍니다! :)

[BE] 카테고리 API, 공통 기능 구현

---

server/src/controllers/payment.controller.ts
server/src/models/index.ts
server/src/models/payment.ts
server/src/models/user.ts
server/src/models/userPayment.ts
server/src/routers/apis/paymentRouter.ts
server/src/services/payment.service.ts

resolve #19 
유저의 결제수단 추가 및 삭제를 위한 API 기능을 구현합니다.
- 개선 사항이나 의문점이 있다면 코드 리뷰로 추가 부탁드립니다!

[BE] 페이먼트 API 기능 구현

---

client/src/apis/api.ts
client/src/apis/historyAPI.ts
client/src/components/History/historyItem.ts
client/src/index.ts
client/src/lib/woowact/core/Store.ts
client/src/models/History.ts
client/src/pages/MainPage.ts
client/src/utils/money.ts
client/src/utils/url.ts
server/src/controllers/history.controller.ts
server/src/index.ts
server/src/models/history.ts
server/src/routers/apis/historyRouter.ts
server/src/services/history.service.ts
server/utils/date.ts

(작업 내역 한줄로 요약)
- 데모를 위해 시범적으로 만든 컴포넌트라 추 후 리팩토링이 많이 필요합니다 ㅠㅠ

[FE] History Item Component 구현중

---

server/src/controllers/payment.controller.ts
server/src/controllers/user.controller.ts
server/src/models/user.ts
server/src/routers/apis/userRouter.ts
server/src/services/user.service.ts

데모 시연을 위한 배포를 위해 PR 내용은 일단 생략합니다!

[BE] 유저 API 기능 구현

---

client/src/App.ts
client/src/apis/api.ts
client/src/components/Header/DatePicker.ts
client/src/components/Header/Header.ts
client/src/components/History/HistortySection.ts
client/src/components/History/HistoryList.ts
client/src/components/History/historyItem.ts
client/src/lib/woowact/core/Component.ts
client/src/pages/MainPage.ts
client/src/styles/history/historySection.scss
server/package-lock.json
server/package.json
server/src/index.ts
server/tsconfig.json

CORS 오류 수정 및 컴포넌트 gettor 설정
하위 컴포넌트를 만들었을 때, 
render() 에서
Component._($component) 부르던 방법을 >> $component.html로 변경했습니다~!

[FE, BE] CORS 오류 수정 및 컴포넌트 gettor 설정

---

client/src/apis/api.ts
client/src/apis/authAPI.ts
client/src/apis/userAPI.ts
client/src/components/Modals/CoreModal.ts
client/src/components/Modals/SigninModal.ts
client/src/components/Modals/SignupModal.ts
server/src/controllers/history.controller.ts
server/src/controllers/user.controller.ts
server/src/middlewares/auth.middleware.ts
server/src/routers/apis/auth.router.ts
server/src/routers/apis/user.router.ts
server/src/services/user.service.ts

회원가입 및 로그인 기능 API 연동했습니다!
- 회원가입 및 로그인 성공과 실패 처리에 대한 프로세스가 없습니다!
- 같이 회의하시죠!!! :)

[FE] 회원가입 및 로그인 API 연동

---

client/src/components/Chart/ChartSection.ts
client/src/components/Chart/ChartTagList.ts
client/src/styles/chart/chartSection.scss
client/src/styles/chart/chartTagList.scss
client/src/styles/main/index.scss
client/src/styles/mixins.scss
client/src/utils/categories.ts

도넛 차트를 구현하였습니다!
- 수입, 지출 토글은 캘린더 완료 후 진행 예정입니다!
- 컴포넌트 구조가 지저분하니 따끔한 코멘트 부탁드립니다!

[FE] 차트구현, 도넛 차트

---

client/src/apis/categoryAPI.ts
client/src/apis/historyAPI.ts
client/src/apis/paymentAPI.ts
client/src/components/Common/Dropdown.ts
client/src/components/History/HistortySection.ts
client/src/components/History/historyItem.ts
client/src/components/Modals/AddHistoryModal.ts
client/src/components/Modals/CoreModal.ts
client/src/components/Modals/SigninModal.ts
client/src/components/Modals/SignupModal.ts
client/src/pages/MainPage.ts
client/src/stores/Category.ts
client/src/stores/History.ts
client/src/stores/Payment.ts
client/src/styles/dropdown.scss
client/src/styles/modals/history.scss
client/src/styles/variables.scss
client/src/utils/calendar/calendar.ts
server/src/controllers/payment.controller.ts
server/src/routers/apis/payment.router.ts
server/src/services/category.service.ts
server/src/services/history.service.ts

히스토리 추가 모달창 구현 ㅠㅠ  Validation 체크할게 많아서 너무 힘들었습니다...
https://user-images.githubusercontent.com/35447853/128205860-1f9d9f86-3727-4162-bdeb-492dbbeaf902.mov
- 잘 한건지 모르곘어요...
- 결제수단 추가기능을 만들어야합니다..!

[FE] 히스토리 추가 모달창 구현

---

client/src/apis/api.ts
client/src/components/Calendar/CalendarSection.ts
client/src/components/Chart/ChartSection.ts
client/src/components/Header/DatePicker.ts
client/src/components/Header/Header.ts
client/src/pages/MainPage.ts
client/src/styles/calendar/calendarSection.scss
client/src/styles/header.scss
client/src/styles/history/historySection.scss
client/src/styles/main/index.scss
client/src/styles/responsive.scss
client/src/styles/variables.scss
client/src/utils/calendar/calendar.ts
client/src/utils/calendar/index.scss
server/src/middlewares/auth.middleware.ts

반응형 작업 및 API 리팩토링 처리 했습니다!  
태블릿 ~ 랩탑 사이즈만 작업했으며, 해당 부분은 적응형에 가깝습니다!
(작업 내역 확인하기 편하도록 gif 첨부)
- 오타나 불필요한 코드가 있다면 따끔한 코멘트를 부탁드립니다!
- 테스트를 위한 코드가 많습니다. 주석처리를 했으나 누락한 부분이 있을 수 있습니다...

[FE, BE] 반응형 작업 및 API 리팩토링

---

client/src/apis/api.ts
client/src/components/Modals/AddHistoryModal.ts
client/src/components/Modals/SignupModal.ts
client/src/utils/alert/alert.scss
client/src/utils/alert/alert.ts

간단한 알람창을 만들었습니다.
https://user-images.githubusercontent.com/35447853/128216031-c2ca2ff8-6920-4ae1-b904-e7876696f085.mov

[FE] 알람창 만들기

---

client/src/components/Chart/ChartSection.ts
client/src/components/Chart/ChartToggleButton.ts
client/src/styles/chart/chartSection.scss
client/src/styles/chart/chartToggleButton.scss
client/src/utils/calendar/calendar.ts

차트 토글 기능 구현 및 캘린더 버그 제보받고 수정!
> 캘린더가 정상적으로 동작하는지 다시 한 번 확인부탁드립니다!

[FE] 차트 토글 기능 구현

---

client/src/components/Header/DatePicker.ts
client/src/components/Modals/SigninModal.ts
client/src/components/Modals/SignupModal.ts
client/src/styles/header.scss
client/src/styles/mixins.scss
client/src/styles/modals/signin.scss
client/src/styles/modals/signup.scss
client/src/styles/responsive.scss

작업물에 로고 넣었슴다...!
css 충돌날까봐 피알 날립니다~!

[FE] 로고 넣기

---

client/src/apis/historyAPI.ts
client/src/components/Chart/ChartSection.ts
client/src/components/Chart/LineChart.ts
client/src/components/History/HistoryBrief.ts
client/src/styles/calendar/calendarSection.scss
client/src/styles/chart/chartSection.scss
client/src/styles/chart/chartTagList.scss
client/src/styles/chart/chartToggleButton.scss
client/src/styles/chart/lineChart.scss
client/src/styles/history/historySection.scss
client/src/styles/index.scss
client/src/styles/main/index.scss
client/src/styles/responsive.scss
client/src/styles/variables.scss
client/src/utils/calendar/index.scss
server/src/models/category.ts
server/src/models/history.ts
server/src/services/category.service.ts

차트 API 데이터 동기화 및 반응형 스타일 작업입니다!

[FE] 차트 API 데이터 동기화 및 반응형 스타일 작업

---

client/src/apis/authAPI.ts
client/src/components/Modals/SigninModal.ts
client/src/components/Modals/SignupModal.ts
client/src/styles/modals/signin.scss

[FE] 시연용 로그인 버튼

---

client/src/apis/api.ts
client/src/apis/authAPI.ts
client/src/index.ts
client/src/lib/woowact/core/Component.ts
server/src/controllers/auth.controller.ts
server/src/index.ts

깃헙 로그인 구현 마무리 했습니다~!
- 완전히 급하게 짠 코드라 리펙토링이 절실합니다 ㅠㅠ
- 제가 잠만 좀 자고 바로 개선하겠습니다

[FE] Fe GitHub로그인 마무리..!

---

client/src/components/AddHistory/AddHistoryModal.ts
client/src/components/History/HistoryItem.ts
client/src/utils/calendar/calendar.ts
server/src/index.ts

배포할 때 문제 생겼었던 버그들 commit 합니다~!
- 리펙토링 주말에 짬내서 좀 해볼게요~!

[FE, BE] 배포할 때 문제 생겼었던 버그들 commit!

---

client/src/components/Chart/ChartSection.ts
client/src/styles/chart/chartTagList.scss
server/src/services/history.service.ts
server/src/services/payment.service.ts
server/src/utils/convertScriptText.ts

- 뒤늦게 나마 버그를 잡아봤습니다.. svg에 대한 학습을 충분하게 하지 않은 점에 반성하게 되네요!

[FE, BE] 버그 수정

---

.github/workflows/deploy.yml
.gitignore
client/src/config.ts
client/src/configExample.ts
scripts/after-deploy.sh

[DE] 자동배포 서버쪽 빌드 단계 추가

---

client/src/components/AddHistory/PaymentDropdown.ts
client/src/components/Modals/SigninModal.ts
server/src/models/category.ts
server/src/models/dummy.ts
server/src/models/index.ts
server/src/models/payment.ts
server/src/services/payment.service.ts

더미 데이터(히스토리 600개, 유저 1개) 추가 :)

[BE] 더미 데이터 추가

---

server/src/models/index.ts

[BE] 더미 데이터 조건문 수정

---

server/src/models/dummy.ts

더미데이터 내용 및 날짜 quotation을 삭제하였습니다.

[BE] quotation 제거
